title: Violet - Build Voice Apps
description: Build Great Voice Experiences
google_analytics: UA-109193428-1
release_version: 1.2
permalink: /blog/:year/:month/:day/:title
paginate: 10
paginate_path: /blog/page/:num
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
